config/routes.rb
Awesome4::Application.routes.draw do

  root :to => "home#m"

  get "home/m"

  resources :samples do
    member do
      patch 'grab' => 'samples#grab'
    end
  end

  resources :mixes do
    member do
      get 'tracker' => 'mixes#tracker'
      put 'add_sample' => 'mixes#add_sample'
    end
  end

  resources :importages

  devise_for :musicians

end

app/models/sample.rb
class Sample < ActiveRecord::Base
  has_attached_file :audio

  validates_attachment :audio,
  :presence => true,
  :size => { greater_than: 0 }

  # supported codecs across different browsers still in a state of flux
  do_not_validate_attachment_file_type :audio

  belongs_to :musician
  has_many :mixes, through: :importages
  has_many :importages, dependent: :destroy
  has_many :libraries, through: :importages

  before_create :populate_empty_name

  def populate_empty_name
    if name.blank?
      self.name = self.audio_file_name
    end
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController

  before_action :set_sample, only: [:show, :edit]
  before_action :set_own_sample, only: [:update, :destroy]
  before_action :authenticate_musician!, :except => [:show]

  # adds this sample to the musician's library
  # PUT
  def grab
    sample = Sample.find(params[:id])
    unless current_musician.library.samples.include? sample
      current_musician.library.samples << sample
    end
    respond_to do |format|
      format.json {render :json => sample }
    end
  end

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
    @my_samples = current_musician.library.samples
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create

    @sample = Sample.new(sample_params().merge({ musician_id: current_musician.id}))

    respond_to do |format|
      if @sample.save
        current_musician.library.samples << @sample
        format.html { redirect_to :action => :index, notice: 'Sample was added.' }
        format.json { render action: 'show', status: :created, location: @sample }
      else
        format.html { render action: 'new' }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_own_sample
    @sample = current_musician.samples.find(params[:id])
  end
  
  def set_sample
    @sample = Sample.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sample_params
    params.require(:sample).permit(:name, :audio, :desc)
  end
end

app/views/samples/_display.html.erb
<span class="name"><%= sample.name %></span>
<audio src="<%= sample.audio.url %>" controls></audio>

app/views/samples/_form.html.erb
<%= form_for(@sample, :html => {:multipart => true}) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    (ogg, mp3, or wav work in chrome, no mp3 support 
    in firefox. keep the file sizes small or it will 
    take forever to load) <br />
    <%= f.label :audio %> 
    <%= f.file_field :audio %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :desc %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/index.html.erb
<h1>Samples</h1>
<%= link_to 'New Sample', new_sample_path %>
<table>

  <script type="text/javascript">
    var musicianId = <%= current_musician.id %>;
  </script>

  <% @samples.each do |sample| %>
  <tr>
    <td><%= sample.name %></td>
    <td><%= sample.desc %></td>
    <td><audio src="<%= sample.audio.url %>" controls></audio></td>
    <td>uploaded by <%= sample.musician.try(:name) %></td>

    <td>
      <% if @my_samples.include? sample %>
        (in library)
      <% else %>
      <%= link_to 'add to library', 
          grab_sample_url(sample, :format => :json), 
          :method => :patch,
          remote: true,
          class: 'grab-sample',
          id: "sample-#{sample.id}" %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sample.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @sample.desc %>
</p>

<p>
  <b>Musician:</b>
  <%= @sample.musician_id %>
</p>


<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>