config/routes.rb
Awesome4::Application.routes.draw do

  root :to => "home#m"

  get "home/m"

  resources :samples do
    member do
      patch 'grab' => 'samples#grab'
    end
  end

  resources :mixes do
    member do
      get 'tracker' => 'mixes#tracker'
      put 'add_sample' => 'mixes#add_sample'
    end
  end

  resources :importages

  devise_for :musicians

end

app/models/musician.rb
class Musician < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :recoverable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :rememberable, :trackable, :validatable

  has_many :samples
  has_many :mixes
  has_one :library, :dependent => :destroy

  before_create :setup_library
  after_create :first_samples

  def name
    email.split('@')[0]
  end

  private
  def setup_library
    if library.nil?
      self.library = Library.create()
    end
  end

  # give new users something to get started with
  def first_samples
    self.library.samples << Sample.first(3)
  end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
  # this class is not routed to for the time being

  before_action :authenticate_musician!, :except => [:index, :show]

  # GET /musicians
  def index
    @musicians = Musician.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @musician = Musician.find(params[:id])
  end

  def edit
    @musician = Musician.find(params[:id])
    @sample = Sample.new
    @sample.musician = @musician
  end

end

app/helpers/musicians_helper.rb
module MusiciansHelper
end

app/views/musicians/_form.html.erb
<%= form_for(@musician, :html => {:multipart => true}) do |f| %>
  <% if @musician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@musician.errors.count, "error") %> prohibited this musician from being saved:</h2>

      <ul>
      <% @musician.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musicians/edit.html.erb
<div style="float: right">
<h3>mixes <%= link_to '(new)', new_mix_url() %> </h3>
<ul>
<% @musician.mixes.each {|m| %>
<li><%= link_to m.name, edit_mix_url(m) %></li>
<% } %>
</ul>

<h3>samples </h3>
<ul>
<% @musician.samples.each {|s| %>
<li><%= link_to s.name, edit_sample_url(s) %></li>
<% } %>
</ul>

<h3> library </h3>
<ul>
<% @musician.library.samples.each {|s| %>
<li><%= link_to s.name, edit_sample_url(s )%></li>
<% } %>
</ul>
</div>

<h1>Editing musician</h1>

<%= render 'form' %>

<%= link_to 'Show', @musician %> |
<%= link_to 'Back', musicians_path %>

<h2> add sample </h2>
<%= render :partial => 'samples/form', :locals => { :sample => @sample } %>

app/views/musicians/index.html.erb
<h1>Listing Musicians</h1>

<table>
  <tr>
    <th>Name</th>
    <th>email</th>
  </tr>

<% @musicians.each do |sample| %>
  <tr>
  
<td><%= sample.email %></td>
    <td><%= link_to 'Show', sample %></td>
    <td><%= link_to 'Edit', edit_musician_path(sample) %></td>
    <td><%= link_to 'Destroy', sample, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Musician', new_musician_path %>

app/views/musicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @musician.email %>
</p>
<p>
<b>Member Since:</b>
<%= @musician.created_at %>
</p>
<p>
  <b>Samples:</b>
  <ul>
    <% @musician.samples.each do |s| %>
      <li>
        <%= link_to 'add to library', 
           {:action => :grab, :sample => s} %>
        <%= s.name %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_musician_path(@musician) %> |
<%= link_to 'Back', musicians_path %>