config/routes.rb
Awesome4::Application.routes.draw do

  root :to => "home#m"

  get "home/m"

  resources :samples do
    member do
      patch 'grab' => 'samples#grab'
    end
  end

  resources :mixes do
    member do
      get 'tracker' => 'mixes#tracker'
      put 'add_sample' => 'mixes#add_sample'
    end
  end

  resources :importages

  devise_for :musicians

end

app/models/importage.rb
class Importage < ActiveRecord::Base
  belongs_to :mix
  belongs_to :sample
  belongs_to :library
end

app/controllers/importages_controller.rb
class ImportagesController < ApplicationController
  before_action :set_importage, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_musician!, :except => [:show]

  # GET /importages
  # GET /importages.json
  def index
    @importages = Importage.all
  end

  # GET /importages/1
  # GET /importages/1.json
  def show
  end

  # GET /importages/new
  def new
    @importage = Importage.new
  end

  # GET /importages/1/edit
  def edit
  end

  # POST /importages.json
  def create
    @importage = Importage.new(importage_params)

    respond_to do |format|
      if ownership_check(@importage) && @importage.save
        format.json { render action: 'show', status: :created, location: @importage }
      else
        format.json { render json: @importage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /importages/1.json
  def update

    respond_to do |format|
      if ownership_check(@importage) && @importage.update(importage_params)
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @importage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /importages/1.json
  def destroy
    if ownership_check(@importage)
      eximportage = @importage.destroy
      respond_to do |format|
        format.json { render :text => "{\"deleted\": #{eximportage.id}}" }
      end
    else
      respond_to do |format|
        format.json { render :text => "{\"not-deleted\": #{@importage.id}}" }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_importage
    @importage = Importage.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def importage_params
    params.require(:importage).permit(:start_time, :simple_volume)
  end

  # make sure the current_musician has the rights to edit this
  def ownership_check(importage)
    unless importage.library_id.nil? ^ importage.mix_id.nil?
      raise 'importage #{importage.id} is orphaned or binding a sample to a library and a mix'
    end
    # if a mix importage verify mix.musican
    if importage.mix_id && (importage.mix.musician_id == current_musician.id)
      true
      # if a library importage verify library.musican
    elsif importage.library_id && (importage.library.musician_id == current_musician.id)
      true
    else
      false
    end
  end
end

app/views/importages/_form.html.erb
<%= form_for(@importage) do |f| %>
  <% if @importage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@importage.errors.count, "error") %> prohibited this importage from being saved:</h2>

      <ul>
      <% @importage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mix_id %><br />
    <%= f.text_field :mix_id %>
  </div>
  <div class="field">
    <%= f.label :sample_id %><br />
    <%= f.text_field :sample_id %>
  </div>
  <div class="field">
    <%= f.label :simple_volume %><br />
    <%= f.text_field :simple_volume %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.text_field :start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/importages/index.html.erb
<h1>Listing importages</h1>

<table>
  <tr>
    <th>Mix</th>
    <th>Mix-lookup</th>
    <th>Library</th>
    <th>Sample</th>
    <th>Simple volume</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @importages.each do |importage| %>
  <tr>
    <td><%= importage.mix_id %></td>
    <td><%= importage.mix_id ? Mix.where(id: importage.mix_id).pluck(:name).to_a : '' %></td>
    <td><%= importage.library_id %></td>
    <td><%= importage.sample_id %></td>
    <td><%= importage.simple_volume %></td>
    <td><%= link_to 'Show', importage %></td>
    <td><%= link_to 'Edit', edit_importage_path(importage) %></td>
    <td><%= link_to 'Destroy', importage, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Importage', new_importage_path %>

app/views/importages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mix:</b>
  <%= @importage.mix_id %>
</p>

<p>
  <b>Sample:</b>
  <%= @importage.sample_id %>
</p>

<p>
  <b>Simple volume:</b>
  <%= @importage.simple_volume %>
</p>


<%= link_to 'Edit', edit_importage_path(@importage) %> |
<%= link_to 'Back', importages_path %>