config/routes.rb
Awesome4::Application.routes.draw do

  root :to => "home#m"

  get "home/m"

  resources :samples do
    member do
      patch 'grab' => 'samples#grab'
    end
  end

  resources :mixes do
    member do
      get 'tracker' => 'mixes#tracker'
      put 'add_sample' => 'mixes#add_sample'
    end
  end

  resources :importages

  devise_for :musicians

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesome</title>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>

  <%= csrf_meta_tags %>
</head>
<body>
<p>
<%  if Rails.env.development? %>
<%    %w(/samples /mixes /importages /musicians/edit /musicians ).each do |l| %>
<%=   link_to l, l %>
<%    end          %>
<%  end            %>
</p>

<p>
<%   if musician_signed_in?                       %>
<%=    link_to current_musician.name + ' samples tracks', home_m_url  %>
<%   else                                         %>
<%=    link_to 'sign in', new_musician_session_url    %> 
<%   end                                         %>
| <%= link_to 'all tracks', mixes_path %>
| <%= link_to_if(musician_signed_in?, :logout, destroy_musician_session_url, method: :delete) %>
</p>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://scrollassets.s3.amazonaws.com/assets/published_initializer-aeba29fe258c77aa7fae941dac725c94.css" media="screen" rel="stylesheet" type="text/css" />

    <style>
      #strip_28552{height:1100px;position:relative;opacity:1;-webkit-background-size:cover;-moz-background-size:cover;-ms-background-size:cover;-o-background-size:cover;background:url('/images/nyc.jpg') 50% no-repeat;background-size:cover;overflow:hidden;}#strip_28552 .frame {width:536px;margin:auto;position:relative;}#el_28552_0{left:-143px;top:141px;position:absolute;outline:none;word-wrap:break-word;-webkit-transform:rotate(0deg);overflow:hidden;width:801px;height:438px;z-index:0;-moz-transform:rotate(0deg);-ms-transform:rotate(0deg);-o-transform:rotate(0deg);-moz-border-radius:66px;-webkit-border-radius:66px;-ms-border-radius:66px;-o-border-radius:66px;border-radius:66px;background-color:rgb(255, 255, 255);-webkit-animation-duration:3900.0000000000005ms;-moz-animation-duration:3900.0000000000005ms;-o-animation-duration:3900.0000000000005ms;-ms-animation-duration:3900.0000000000005ms;}#el_28552_1{position:absolute;outline:none;word-wrap:break-word;-webkit-transform:rotate(0deg);overflow:hidden;font-size:24px;line-height:36px;padding-left:3px;padding-right:3px;color:#6f0c0c;text-align:left;width:231px;top:192px;left:-97px;z-index:1;font-family:"Fenix";-moz-transform:rotate(0deg);-ms-transform:rotate(0deg);-o-transform:rotate(0deg);-webkit-animation-duration:3680ms;-moz-animation-duration:3680ms;-o-animation-duration:3680ms;-ms-animation-duration:3680ms;}

      #el_28552_2{color:#6f0c0c;font-family:Fenix;line-height:24px;font-size:16px;position:absolute;outline:none;word-wrap:break-word;-webkit-transform:rotate(0deg);overflow:hidden;padding-left:3px;padding-right:3px;text-align:left;width:286px;top:232px;left:-97px;z-index:2;-moz-transform:rotate(0deg);-ms-transform:rotate(0deg);-o-transform:rotate(0deg);-webkit-animation-duration:3680ms;-moz-animation-duration:3680ms;-o-animation-duration:3680ms;-ms-animation-duration:3680ms;}

      #el_28552_3{position:absolute;outline:none;word-wrap:break-word;-webkit-transform:rotate(0deg);overflow:hidden;font-size:24px;line-height:36px;padding-left:3px;padding-right:3px;color:#6f0c0c;text-align:left;width:231px;top:192px;left:287px;z-index:3;font-family:"Fenix";-moz-transform:rotate(0deg);-ms-transform:rotate(0deg);-o-transform:rotate(0deg);-webkit-animation-duration:3680ms;-moz-animation-duration:3680ms;-o-animation-duration:3680ms;-ms-animation-duration:3680ms;}


      #el_28552_4{color:#6f0c0c;font-family:Fenix;line-height:24px;font-size:16px;position:absolute;outline:none;word-wrap:break-word;-webkit-transform:rotate(0deg);overflow:hidden;padding-left:3px;padding-right:3px;text-align:left;width:286px;top:232px;left:288px;z-index:4;-moz-transform:rotate(0deg);-ms-transform:rotate(0deg);-o-transform:rotate(0deg);-webkit-animation-duration:3680ms;-moz-animation-duration:3680ms;-o-animation-duration:3680ms;-ms-animation-duration:3680ms;}
    </style>

    <%= csrf_meta_tags %>

  </head>
  <body>


    <%= yield %>

  </body>
</html>